spring.application.name=ai-mcp-client
server.port=8081

# Connect to the MCP Server URL including the full endpoint path
spring.ai.mcp.client.streamable-http.connections.hotel-server.url=http://ai-mcp-sandbox-service:8080/mcp
spring.ai.mcp.client.streamable-http.connections.hotel-server.request-timeout=60s

# Google GenAI Configuration
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash