spring.application.name=ai-mcp-sandbox
# Give your MCP server a name
spring.ai.mcp.server.name=hotel-mcp-server

# Enable the server and set the communication protocol
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.protocol=STREAMABLE

# Connects directly to Qdrant inside GCP GKE Cluster
spring.ai.vectorstore.qdrant.host=qdrant-service
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=hotel_embeddings

# GCP Gemini Text Embedding Configuration
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.model=text-embedding-004