name: 2-devops-tools

on:
  workflow_run:
    workflows: ["1-infrastructure"]
    types: [completed]
  push:
    branches: [ main ]
    paths: [ 'k8s/devops-tools/**' ]
  workflow_dispatch:

jobs:
  deploy-tools-to-azure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: 'hotel-devops-rg'
          cluster-name: 'hotel-devops-aks'

      - name: Deploy DevOps Stack to AKS
        run: |
          kubectl apply -f k8s/devops-tools/